services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: request-pro-backend-container
    restart: always
    volumes:
      - backend:/usr/src/app
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://request-pro-mysql:3306/request_pro_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      MAIL_HOST: mail
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      - mysql
    networks:
      - request-pro-network

  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
      args:
        VITE_API_URL: http://localhost:8084
    container_name: request-pro-web-container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - request-pro-network
    depends_on:
      - backend