services:
  mysql:
    image: mysql:8.0
    container_name: request-pro-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: request_pro_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - request-pro-network

volumes:
  mysql:
    name: request-pro-mysql
  backend:
    name: request-pro-backend

networks:
  request-pro-network:
    driver: bridge
