FROM node:18-alpine as build

WORKDIR /app

COPY ../web/package.json ../web/package-lock.json ./

RUN npm install

COPY ../web .

ARG VITE_API_URL

RUN npm run build

FROM node:18-alpine as production

WORKDIR /app

COPY --from=build /app/dist /app/dist

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]
