DROP DATABASE IF EXISTS request_pro_db;
CREATE DATABASE IF NOT EXISTS request_pro_db;

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON request_pro_db.* TO 'user'@'%';

FLUSH PRIVILEGES;